name: CI

on:
  push:
  pull_request:

env:
  OPENSEARCH_VERSION: "3.2.0"
  VERSION: "3.2.0.0"   # security plugin version

jobs:
  test-no-plugins:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5

      - uses: ./ # Use the action
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          security-enabled: false

      - name: Checks that OpenSearch is healthy
        run: curl http://localhost:9200/_cat/plugins -v
        shell: bash

  test-no-plugins-port-9201:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5

      - uses: ./ # Use the action
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          security-enabled: false
          port: 9201

      - name: Checks that OpenSearch is healthy
        run: curl http://localhost:9201/_cat/plugins -v
        shell: bash

  test-with-security:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5

      - name: Download security plugin
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-security/${{ env.VERSION }}/opensearch-security-${{ env.VERSION }}.zip
          filename: security.zip

      - uses: ./ # Use the action
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          security-enabled: true
          plugins: "file:${{ github.workspace }}/security.zip"
          admin-password: "myStrongPassword123!"

      - name: Checks that OpenSearch is healthy
        run: curl https://localhost:9200/_cat/plugins -u 'admin:myStrongPassword123!' -k -v
        shell: bash